### ISSUE TITLE
tags not accepted when editing lasted post plugin

### ISSUE THREAD

**Issue by rikaa** [nephila/djangocms-blog#188]
Hi,
when I edit an instance of the latest post plugin, the selected tags are not accepted. Instead, an error message appears saying that a list  is required which contains values. 

Here is a screen shot of the error message

<img width="921" alt="screen shot 2016-01-11 at 11 27 31" src="https://cloud.githubusercontent.com/assets/12941367/12231320/da6edc0c-b856-11e5-927b-33eea3c6a37b.png">

Cheers

**Comment by yakky** [comment]
I can't reproduce on latest djangocms blog. which version are you using?

**Comment by rikaa** [comment]
I'm using version 0.5.0

**Comment by yakky** [comment]
Tag selectoin has been reworked in 0.6.0. Any reason not to upgrade?

**Comment by rikaa** [comment]
updating to 0.6.0 raises this error

django.db.utils.IntegrityError: column "app_config_id" contains null values

**Comment by yakky** [comment]
@rikaa which Django version? Migrations should take care to generate app_configs for existing posts

**Comment by yakky** [comment]
(with 0.6.0 I meant 0.6.3, sorry)

**Comment by rikaa** [comment]
with 0.6.3, I get this error

AttributeError: 'NoneType' object has no attribute 'pk'

from 
python2.7/site-packages/djangocms_blog/menu.py , line 57, in get_nodes

**Comment by yakky** [comment]
@rikaa apparently some post have no category attached, which should not be allowed, could you check that?
Also does every post has a apphook config attached now?

**Comment by rikaa** [comment]
I installed 0.6.3 and assigned a category to each post, and it's working now.
Thanks!

**Comment by yakky** [comment]
@rikaa thanks for the feedback, probably I'll add some information to help other users migrating from 0.5 to 0.6

**Comment by yakky** [comment]
Added documentation regarding the original issue and the upgrade issues.
Thanks again @rikaa
